name: 2026_tricomm
channels:
  - conda-forge
  - bioconda
dependencies:
- python
- pandas
- openpyxl
- numpy
- scipy
- matplotlib
- seaborn
- jupyterlab
- nbconvert
- octave
- pip:
  - git+https://github.com/microbial-pangenomes-lab/plate_reader_evolution.git
